Update typo in realtime_updates.py
missing a "s" for "admins" in:
`await pb.admins.auth.with_password(email=ADMIN_EMAIL, password=ADMIN_PASSWORD)`

causing the error:
`    await pb.admin.auth.with_password(email=ADMIN_EMAIL, password=ADMIN_PASSWORD)
          ^^^^^^^^
AttributeError: 'PocketBase' object has no attribute 'admin'. Did you mean: 'admins'?`